[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
on_event = "InsertEnter"
depends = 'context_filetype.vim'
hook_source = '''
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#enable_ignore_case = 1
	let g:deoplete#enable_smart_case = 1
'''

[[plugins]]
repo = 'padawan-php/deoplete-padawan'
depends = ['deoplete.nvim']
on_ft = 'php'
hook_post_source = '''
	call deoplete#sources#padawan#StartServer()
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
on_ft = ['c', 'cpp']
hook_source = '''
	let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
	let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/5.0.0/include/clang'
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
depends = ['deoplete.nvim']
on_ft = 'rust'
hook_source = '''
	let g:deoplete#sources#rust#racer_binary='/Users/shunsuke/.cargo/bin/racer'
	let g:deoplete#sources#rust#rust_source_path='/Users/shunsuke/rust-src/rust/src'
	let g:deoplete#sources#rust#show_duplicates=1
'''
