# plugins in this file are read every time

[[plugins]]
repo = 'Shougo/dein.vim'

# easy comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# change "" , '' , () , and more
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'yggdroot/indentLine'
hook_source = '''
	let g:indentLine_enabled = 1
	let g:indentLine_char = '|'
	let g:indentLine_color_term = 239
	" Background (Vim, GVim)
	let g:indentLine_bgcolor_term = 202
	let g:indentLine_bgcolor_gui = '#FF5F00'
'''


# ---------- color schemes ----------------

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'morhetz/gruvbox'
