# plugins in this file are read every time

[[plugins]]
repo = 'Shougo/dein.vim'

# easy comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# change "" , '' , () , and more
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
let g:airline#extensions#hunks#enabled = 0
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = '''
#   let g:indent_guides_enable_on_vim_startup = 1
# 	let g:indent_guides_guide_size = 1
# 	let g:indent_guides_start_level = 2
# 	" autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#444433 ctermbg=black
# 	" autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray
# '''
# hook_source = '''
# 	let g:indent_guides_guide_size = 1
# 	let g:indent_guides_start_level = 2
# 	" autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#444433 ctermbg=black
# 	" autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray
# '''

# [[plugins]]
# repo = 'Yggdroot/indentLine'
# hook_source = '''
# 	let g:indentLine_enabled = 1
# 	let g:indentLine_char = '|'
# 	let g:indentLine_color_term = 239
# 	" Background (Vim, GVim)
# 	let g:indentLine_bgcolor_term = 202
# 	let g:indentLine_bgcolor_gui = '#FF5F00'
# '''


# ---------- color schemes ----------------

[[plugins]]
repo = 'morhetz/gruvbox'

# ---------- other languages --------------

# for Elixir
[[plugins]]
repo = 'elixir-lang/vim-elixir'

# window resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-W><C-R>'
'''
