[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
	let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'padawan-php/deoplete-padawan'
depends = ['deoplete.nvim']
on_ft = 'php'

[[plugins]]
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
on_ft = ['c', 'cpp']
hook_source = '''
	let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
	let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/5.0.0/include/clang'
'''
