[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
on_event = "InsertEnter"
depends = 'context_filetype.vim'
hook_source = '''
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#enable_ignore_case = 1
	let g:deoplete#enable_smart_case = 1
	" <TAB>: completion
	imap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : <SID>check_back_space() ? "\<TAB>" : deoplete#mappings#manual_complete()
	function! s:ckech_back_space() abort
		let col = col('.')[col - 1] =~ '\s'
	endfunction
	" <S-TAB>: completion back
	inoremap <expr><S-TAB> pubvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]]
repo = 'padawan-php/deoplete-padawan'
depends = ['deoplete.nvim']
on_ft = 'php'

[[plugins]]
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
on_ft = ['c', 'cpp']
hook_source = '''
	let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
	let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/5.0.0/include/clang'
'''
